name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    # Instala Gradle (para generar el wrapper)
    - name: Install Gradle
      run: |
        sudo apt-get update
        sudo apt-get install -y gradle

    # Genera el Gradle Wrapper (usando la versión compatible con tu proyecto)
    - name: Generate Gradle Wrapper
      run: |
        gradle wrapper --gradle-version 8.4 --distribution-type bin
        chmod +x gradlew

    # Verifica que el wrapper se generó correctamente
    - name: List generated files
      run: |
        ls -la
        ls -la gradle/wrapper/

    # Compila el proyecto Android
    - name: Build with Gradle
      run: ./gradlew build

    # (Opcional) Sube el APK como artefacto
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release
        path: app/build/outputs/apk/**/*.apk